### ISSUE TITLE
will_paginate gem does not work with padrino

### ISSUE THREAD

**Issue by rbrigby** [mislav/will_paginate#149]
my padrino app is configured as follows.  The gem installs just fine, but when i run padrino i get an error.  Any help will be much appreciated.
# gemfile

gem 'will_paginate', '~> 3.0.pre4'
# boot.rb

require 'will_paginate'
require 'will_paginate/active_record'

/Users/rbrigby/src/xav/config/boot.rb:9:in `require': no such file to load -- will_paginate/active_record (LoadError)
    from /Users/rbrigby/src/xav/config/boot.rb:9:in`<top (required)>'
    from /Users/rbrigby/.rvm/gems/ruby-1.9.2-p290/gems/padrino-core-0.10.0/lib/padrino-core/cli/base.rb:23:in `require'
    from /Users/rbrigby/.rvm/gems/ruby-1.9.2-p290/gems/padrino-core-0.10.0/lib/padrino-core/cli/base.rb:23:in`start'
    from /Users/rbrigby/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/rbrigby/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:118:in`invoke_task'
    from /Users/rbrigby/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/rbrigby/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /Users/rbrigby/.rvm/gems/ruby-1.9.2-p290/gems/padrino-core-0.10.0/bin/padrino:9:in `<top (required)>'
    from /Users/rbrigby/.rvm/gems/ruby-1.9.2-p290/bin/padrino:19:in`load'
    from /Users/rbrigby/.rvm/gems/ruby-1.9.2-p290/bin/padrino:19:in `<main>'

**Comment by onetechlabs** [comment]
undefined method `paginate' for Account:Class i got this error , how to fix it on padrino ? im installing using command padrino g plugin will_paginate
