### ISSUE TITLE
Please provide a working example of overriding LinkRenderer

### ISSUE THREAD

**Issue by ghost** [mislav/will_paginate#158]
I can override LinkRenderer in the Git version, but when I call it I get a NotImplementedError for the #url method.  It's not clear what the "correct" way to override this functionality is, but overriding #to_html alone does not appear to be sufficient.

If you could add an article on how to do this, it would really help.  Thanks!

**Comment by maxfwerner** [comment]
I created a gist with a fully working rails AJAX paginator with bootstrap 4 styling applied (should work for bootstrap 3 too). You can find it here:

https://gist.github.com/maxfwerner/edcb89db77e9e2a3f521

**Comment by zandroid** [comment]
There is an example of custom renderer for Bootstrap 4 (alpha 4) https://gist.github.com/zandroid/8ed85b518fd3ce441f0864477aa7eb86

**Comment by el-yomi** [comment]
Here is an example of custom renderer for Bulma (0.3.2)
**bulma_pagination_helper.rb**
`
module BulmaPaginationHelper
  class LinkRenderer < WillPaginate::ActionView::LinkRenderer
    protected

    def html_container(html)
      tag(:nav, tag(:ul, html, class: "pagination-list"), class: "pagination is-centered")
    end

    def previous_or_next_page(page, text, classname)
      if page
        tag(:li, link(text, page, class: "pagination-link"))
      else
        tag(:li, tag(:a, text, class: "pagination-link"), class: "is-disabled")
      end
    end

    def page_number(page)
      unless page == current_page
        tag(:li, link(page, page, class: "pagination-link"))
      else
        tag(:li, tag(:a, page, class: "pagination-link is-current"))
      end
    end

    def gap
      tag(:li, tag(:span, '&hellip;', class: "pagination-ellipsis"))
    end

  end

  def bulma_will_paginate(collection = nil, options = {})
    options, collection = collection, nil if collection.is_a? Hash
    options = options.merge(
      renderer: BulmaPaginationHelper::LinkRenderer,
    )
    will_paginate(collection, options)
  end

end
`

Example of usage: just _bulma_will_paginate_

**Comment by blairanderson** [comment]
here is a tutorial for creating a [custom will_paginate renderer](https://www.tachyonstemplates.com/2017/custom-renderer-will-paginate/)
