### ISSUE TITLE
undefined method `paginate' for Arrays

### ISSUE THREAD

**Issue by michaelrigart** [mislav/will_paginate#163]
Since version 3.0.0, the Array class extension with pagination isn't included in the core_ext.rb file:

require 'will_paginate/array'

Or anywhere else for that mather it seems.

Is this the wanted behavior and does the user has to include the array extension themselves?
https://github.com/mislav/will_paginate/commit/903950020764618d01c72d624aa78867ed397ae8

**Comment by arif362** [comment]
yes. thanks for correct info @fschwahn
