### ISSUE TITLE
will_paginate initializer now throws NameError error

### ISSUE THREAD

**Issue by npadgett** [mislav/will_paginate#165]
My initializers file is named 'config/initializers/will_paginate.rb' and includes the following.

WillPaginate::ViewHelpers.pagination_options[:previous_label] = '&lsaquo;'
WillPaginate::ViewHelpers.pagination_options[:next_label] = '&rsaquo;'

This is the error that is thrown when I run 'rails s':

/Users/ysername/projects/project/config/initializers/will_paginate.rb:3: uninitialized constant WillPaginate::ViewHelpers (NameError)

This occurs with will_paginate 3.0.pre4 and 3.0.0.

I'm using Rails 3.0.10.

**Comment by NikitaShmelev** [comment]
minus 1
