### ISSUE TITLE
undefined local variable or method `per' for []:ActiveRecord::Relation

### ISSUE THREAD

**Issue by bitcoiners** [mislav/will_paginate#174]
Hello,
After adding will_paginate to my Gemfile I get this error:

```
gem 'will_paginate', :git => 'git://github.com/mislav/will_paginate.git'

undefined local variable or method `per' for []:ActiveRecord::Relation

Rails.root: /home/slava/dev/projects/bitcoin-derivatives
Application Trace | Framework Trace | Full Trace

activerecord (3.1.0) lib/active_record/relation.rb:459:in `method_missing'
/home/slava/.rvm/gems/ruby-1.9.2-p290/bundler/gems/spree-037b9258f970/core/lib/spree/search/base.rb:15:in `retrieve_products'
/home/slava/.rvm/gems/ruby-1.9.2-p290/bundler/gems/spree-037b9258f970/core/app/controllers/home_controller.rb:7:in `index'
```

**Comment by mplewis** [comment]
I'm using RefineryCMS with Spree Commerce. Here's what my dependencies look like:

    refinerycms (3.0.0)
      refinerycms-core (3.0.0)
        will_paginate (~> 3.0.2)

    spree_core (3.0.1)
      kaminari (~> 0.15, >= 0.15.1)

I put the following in `config/initializers/kaminari_config.rb` to solve this problem:

```rb
if defined?(WillPaginate)
  module WillPaginate
    module ActiveRecord
      module RelationMethods
        alias_method :per, :per_page
        alias_method :num_pages, :total_pages
        alias_method :prev_page, :previous_page
      end
    end
  end
end
```

**Comment by SanjayYadav90** [comment]
Actually ctiveAdmin uses Kaminari for pagination
We have used will_paginate in your app, due to that pagination get conflict, 
to remove this conflicts.
Just create kaminari.rb file in your "config/initializers/kaminari.rb"
and type this code in it.
Kaminari.configure do |config|
  config.page_method_name = :per_page_kaminari
end
Restart the server again and hope the issue get resolved.

**Comment by quocnv** [comment]
Thanks

**Comment by hoangvq288** [comment]
Thanks. It worked for me

**Comment by artemdev** [comment]
thanks!
