### ISSUE TITLE
SEO optimize pagination with rel="prev" & rel="next"

### ISSUE THREAD

**Issue by Rio517** [mislav/will_paginate#183]
I wanted to propose that will_paginate include a view helper for SEO optimization, per a recent official Google blog post

```
<link rel="prev" href="http://www.example.com/article?story=abc&page=1&sessionid=123" />
<link rel="next" href="http://www.example.com/article?story=abc&page=3&sessionid=123" />
```

link: http://googlewebmastercentral.blogspot.com/2011/09/pagination-with-relnext-and-relprev.html

Thanks!

**Comment by johnpash** [comment]
:+1:

**Comment by subimage** [comment]
MISLAV WHY U NO MERGE :(

**Comment by scruti** [comment]
:clock1130:

**Comment by aleks** [comment]
We are in need of this too! A merge would be kinda cool. :+1:

**Comment by ryanahamilton** [comment]
:+1:

**Comment by noafroboy** [comment]
:+1:

**Comment by alpemaca** [comment]
:+1:

**Comment by jonatack** [comment]
Folks, `+1` comments are unhelpful. if you want this feature or any other, just fork the gem and merge it in. This is open source; do what you want :smiley:

**Comment by mpolakis** [comment]
Thanks @lloydmeta and @jonatack for your work on this issue. Also, thanks @mislav for building this wonderful gem. Any idea if you actually intend to merge this? If yes, when? Thanks.

**Comment by dignoe** [comment]
I've made a gist on how to monkey patch will_paginate v3.0.7 to add rel="next" & rel="prev" links to your header. I only use this on pages that require custom link generation, so this also includes a patch to use a custom url generator if a specific option is passed.

https://gist.github.com/dignoe/0f76e81949b46e48e4ff4f992aa93aeb

**Comment by erpe** [comment]
if you don't like monkey patching: a simple view-helper as a rails-railtie: https://github.com/erpe/rails_will_paginate_seo_helper

**Comment by mislav** [comment]
Decided not to go with this feature and forgot to close this. https://github.com/mislav/will_paginate/pull/324#issuecomment-836507422
