### ISSUE TITLE
undefined method `total_pages' for #<Array:0xb3da36f4>

### ISSUE THREAD

**Issue by railsfactory-dhibika** [mislav/will_paginate#195]
In controller i have added the code

```
@partner_deals=(Partner.find_by_id(params[:id]).deals.reject{|x| x.deal_date>Date.today}).paginate(:page => params[:page],:per_page => 2)   
```

i added require 'will_paginate/array' in controller 

In view

<%= will_paginate @partner_deals %>

but the error "undefined method `total_pages' for #Array:0xb3da36f4"  shows

**Comment by Nowaker** [comment]
It's still a problem. I don't see how https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/array.rb can fix it. It does not introduce the missing `total_pages` method to the array objec.t
