### ISSUE TITLE
Removing next link causes last page to repeat

### ISSUE THREAD

**Issue by johngrimes** [mislav/will_paginate#3]
There seems to be a problem when you remove the next link by setting the next_link parameter to nil on the will_paginate method.

It seems to result in the link for the last page being repeated.

For example:
« Previous 1 2 2

**Comment by mislav** [comment]
You're not supposed to have a simple venue for removing the next page link. The next page link is the most important link of pagination.

You can, however, make a custom link rendered and change *any* aspect of HTML that's being output. See my comment in https://github.com/mislav/will_paginate/pull/484#issuecomment-252927444

Example:

```rb
class NoNextPage < WillPaginate::ActionView::LinkRenderer
  def pagination
    super.reject { |item| item == :next_page }
  end
end
```
