### ISSUE TITLE
I Can't install will_paginate

### ISSUE THREAD

**Issue by sbrocos** [mislav/will_paginate#311]
I have got a problem when I want install this gem
My GemFile:
  gem 'rails', '3.2.13'
  gem 'bootstrap-sass', '2.1'
  gem 'bcrypt-ruby', '3.0.1'
  gem 'faker', '1.0.1'
  gem 'will_paginate', '~> 3.0.4'
  gem 'bootstrap-will_paginate', '0.0.6'
  gem 'jquery-rails', '2.0.2'
The result of bundle install/update:
  bundle install --without production
  Fetching gem metadata from https://rubygems.org/.........
  Fetching gem metadata from https://rubygems.org/..
  Resolving dependencies...
  Could not find gem 'will-paginate (= 3.0.3) ruby' in the gems available on this machine.

**Comment by vsquared10** [comment]
mind sharing what the error was that you fixed?
