### ISSUE TITLE
Support for two queries pagination: first paginate only `id` field and then select records by ids

### ISSUE THREAD

**Issue by leschenko** [mislav/will_paginate#334]
For pagination in large tables with many columns sometimes we can get better performance with two queries pagination:

1) paginate only with `id` column

``` sql
SELECT `products`.id FROM `products` LIMIT 30 OFFSET 30
```

2) select records by ids

``` sql
SELECT `products`.* FROM `products` WHERE `products`.`id` IN (1, 2, 3, 4, 5)
```

It will be nice to have something like `large` option in `paginate` method for two queries pagination.

**Comment by mislav** [comment]
https://github.com/mislav/will_paginate/wiki#limitations
