### ISSUE TITLE
Pagination happened to show "Page Gap"

### ISSUE THREAD

**Issue by andrewleo** [mislav/will_paginate#346]
When I use the code below to realize paging, unnomal situation happened as the attachment showing, just as the title says:

```
  <%= will_paginate @apks, :previous_label => '上一页', :next_label => '下一页' %>
```

![2013-12-11 11 57 18](https://f.cloud.github.com/assets/3241895/1721958/3532297a-6235-11e3-9aa2-4cd415bfd6da.png)

I alse observe the source code of html ：

```
<span class="gap">
    <span class="translation_missing" title="translation missing: zh.will_paginate.page_gap"></span>
</span>
```

What version of the product are you using? On what operating system?
will_paginate 3.0.5,Mac OS X 10.7.5

Wish you can help,many thanks!

**Comment by lonely21475** [comment]
file path
config/locales.yml
add like this
will_paginate:
    previous_label: '<<上一页'
    next_label: '下一页>>'
    page_gap: '....'

that would be ok !!
