### ISSUE TITLE
Default 'page_gap' translation does not work

### ISSUE THREAD

**Issue by vouriotd** [mislav/will_paginate#349]
Without any translation files, when calling will_paginate,  the 'page_gap' label trigger a 'translation missing' label.

The code in
https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/i18n.rb#L11
which, in my opinion, should be called by
https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/view_helpers/link_renderer.rb#L52
is not.

Instead, it is calling the one in
https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/view_helpers/action_view.rb#L74
which does not support the default in the same way.

Did I miss or misunderstood something ?

**Comment by RaphaelAudet** [comment]
I am getting this too
`<%= will_paginate @quantities, :page_gap => "..." %>`

<img width="463" alt="image" src="https://user-images.githubusercontent.com/1086433/50340592-e6720a00-051b-11e9-9a8f-212e39a01b54.png">


Ruby 2.4.2
`
gem 'will_paginate', '~> 3.1.0'
gem 'rails', '~> 5.1.5'
gem 'rails-i18n', '~> 5.0.0'
`

**Comment by mislav** [comment]
Weird! This looks similar to https://github.com/mislav/will_paginate/issues/555. I think the faulty string comes from the translation component, not from will paginate. The translation key is called `will_paginate.page_gap`, and the default value is `…`.
