### ISSUE TITLE
Overzealous match with finder.rb#method_missing_with_paginate?

### ISSUE THREAD

**Issue by xunker** [mislav/will_paginate#35]
I am seeing an issue with 2.3.11 under rspec with rails 2.3.5.  Given I have an activerecord class with a method containing the word 'paginate':

  class Foo << ActiveRecord::Base; def self.paginated_search; end; end

..when attempting to call that method in specs I will be told:

"undefined method ‘findd_search’ for #Class:0x60f2c"

I have traced this down to Finder module in #method_missing_with_paginate where it appears to be patching ActiveRecord's base with a method missing that is calling .sub on the method name that replaces 'paginate' with 'find' and is changing my method call to 'findd_search' (which doesn't exist, of couse)

I have been able to fix problems in my local install by either changing the method name to be something that doesn't contain the word 'paginate' or by patching the method_missing.

For the next version of will_paginate, might it be a good change to switch:

finder.rb:175:
   finder = method.to_s.sub('paginate', 'find')

to something like:
  finder = method.to_s.sub(/^paginate&#95;/, 'find_')

..so that it will only match methods named "paginate&#95;&#42;" and not methods named "is_paginated_&#42;".

**Comment by badbabykosh** [comment]
This is still an issue
