### ISSUE TITLE
NoMethodError: undefined method `encoding' for \d+:Fixnum

### ISSUE THREAD

**Issue by chuckpreslar** [mislav/will_paginate#364]
Located in `/view_helpers/link_renderer.rb` on line 90 there's the following:

```ruby
def link(text, target, attributes = {})
  if target.is_a? Fixnum
    attributes[:rel] = rel_value(target)
    target = url(target)
  end
  attributes[:href] = target
  tag(:a, text, attributes)
end
```

When `target.is_a? Fixnum #=> true`, the `target` is passed to the method `url` where it is combined into a hash along with values for the controller, the action and any additional route parameters.

```ruby
{
   :controller => "foo",
   :action => "bar",
   :page => 2 # `target`
}
```

Eventually CGI::escape is called for each member of the hash to create the final URL.

```ruby
def CGI::escape(string)
  # ...
end
```

Here, `encoding` is called upon the string which is our target resulting in a `NoMethodError`. Modifying the code locally to call `to_s` on the target when the type of Fixnum is detected solves the issue, but I'm going to go out on a limb and assume I'm doing something terribly wrong...

Versions:
```
$ ruby --version
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin13.0.2]
$ rails --version
Rails 4.0.1
```

**Comment by mislav** [comment]
Closing as not an issue, since I haven't received confirmation from other users that this is failing. It might have been a temporary Rails bug.
