### ISSUE TITLE
Is it even possible to show limited count of items on the first page?

### ISSUE THREAD

**Issue by kourindouhime** [mislav/will_paginate#402]
Hi.

Let's pretend that I have 30 @posts overall and 10 posts per page. But the first 5 posts on the 1st page are not selected using the same query as which contains paginate. Those 5 posts are customized by hand, and the other 5 posts on the first page are loaded by

```
Post.order("created_at DESC").paginate(:page => params[:page], :per_page => 10-5)
```

The second page doesn't have posts being customized by hand, so there I'm using same query but with `:per_page => 10`.

And those 5 posts which are being cut on the first page are missing. Can you tell me if it's possible to load 5-15 posts to 2nd page, 15-25 to the 3rd and etc.? Thank you.

Also I've tried using offset, but it doesn't seem to work they way I need.

**Comment by mislav** [comment]
Closing this as something that I can't imagine a way of solving through the will_paginate library. This is best solved in one's own application.
