### ISSUE TITLE
undefined method `total_pages' for #<User::ActiveRecord_Relation:0x000000051b4608>

### ISSUE THREAD

**Issue by MansurAje** [mislav/will_paginate#411]
Hi Mislav, 
I got error in my project with will_paginate, 
i used rails 4 , active record 4, and will_paginate 3.0.7 

in my controller 
@users=User.paginate(:page => params[:page], :per_page => 30)

in my view 
<%= will_paginate @users  %>

always give error 
undefined method `total_pages' for #User::ActiveRecord_Relation:0x000000051b4608

how to solve it,? Thanks

**Comment by samarthsikotara** [comment]
@tcwalther have you solved your above issue?

**Comment by tcwalther** [comment]
@samarthsikotara I'm afraid I haven't, I ended up rewriting my views to have a more AJAX-y application, and thus the precondition of having multiple paginations on a site no more applies.

**Comment by samarthsikotara** [comment]
Ok cool

**Comment by sprite2005** [comment]
I've seen same error in my logs, but I'm unable to reproduce it with my own requests.

015-01-20T01:58:39.753170+00:00 app[web.2]: ActionView::Template::Error (undefined method `total_pages' for #<Server::ActiveRecord_Relation:0x007fd6ad567c10>):
2015-01-20T01:58:39.753172+00:00 app[web.2]:     55:   - if user_signed_in? && current_user.admin?
2015-01-20T01:58:39.753173+00:00 app[web.2]:     56:     = link_to t('.new', :default => t("helpers.links.new")), new_server_path, :class => 'btn btn-primary'
2015-01-20T01:58:39.753175+00:00 app[web.2]:     57:   .pull-right
2015-01-20T01:58:39.753176+00:00 app[web.2]:     58:     = will_paginate @servers
2015-01-20T01:58:39.753177+00:00 app[web.2]:   app/views/servers/index.html.haml:58:in `_app_views_servers_index_html_haml__2495643482479516274_70279949105540'
2015-01-20T01:58:39.753179+00:00 app[web.2]:   app/controllers/servers_controller.rb:17:in `index'

**Comment by Bwian** [comment]
Don't know if this helps, but this occurred for me when, using the original example, @users.size == 0.

**Comment by jbmoutout** [comment]
Hello, I have the same issue here, works fine on localhost but got the following error 500 on Heroku:

```2015-03-20T11:58:35.999449+00:00 app[web.1]: ActionView::Template::Error (undefined method `total_pages' for #<Dialog::ActiveRecord_Relation:0x007f3a3cada700>):
2015-03-20T11:58:35.999456+00:00 app[web.1]:      9:   <%= will_paginate @dialogs %>
2015-03-20T11:58:35.999459+00:00 app[web.1]:   app/views/dialogs/index.html.erb:9:in `_app_views_dialogs_index_html_erb__4301823330575093547_69944063143320'```

Here is my index.html.erb:
```
<div id="dialogs">
  <div class="scroll-top">Back to top</div>
  <% cache("dialog") do  %>
    <%= render "dialog" %>
  <% end %>
</div>

<%# will_paginate @dialogs %>
```
and dialogs_controller.rb:
```
class DialogsController < ApplicationController
  skip_after_action :verify_authorized, only: :collection
  skip_before_action :authenticate_user!

  def index
    @dialogs = policy_scope(Dialog)
    #Working on Heroku (without pagination) :
    @dialogs = Dialog.order('origin_date DESC').includes(:artwork)
    #Need to be fixed (working on local, not on Heroku) :
    #@dialogs = Dialog.order('origin_date DESC').includes(:artwork).page(params[:page])


    @artists = Artist.all
  end
```
 Many thanks for your help

**Comment by Bwian** [comment]
@jbmoutout, I haven't tried to find the underlying problem but there appears to be an issue with empty result sets. The following (in your context) solved the problem for me:

    <% unless @dialogs.empty? %>
      <%= will_paginate @dialogs %>
    <% end %>

**Comment by joemsak** [comment]
+1 for me but @Bwian's suggestion didn't work in my case

**Comment by joemsak** [comment]
The problem for me was that `will_paginate` in the view is being passed an un-paginated collection

I had a conditional that added pagination
```ruby
collection = # ...

if some_option?
  collection = ar_relation.page(params[:page])
end

collection
```

**Comment by Manifold0** [comment]
Still getting this problem in a new application. Initially I was only getting it with blank results, as had been asserted. But even after populating the database and having an Active Record Relation with multiple entries the same error is being generated. It seems like the Relation is not being handled by will_paginate's model tweaking for Rails.

**Comment by rocLv** [comment]
I got this error, too. But I figured out I forgot to user `paginate` in my Model.
```ruby
- @users = User.where('email LIKE ?', '%some%')
+ @users = User.where('email LIKE ?', '%some%').paginate(page: params[:page])
```

**Comment by guilpejon** [comment]
I'm having the exact same problem, but I wasn't able to create an example that could reproduce it.

**Comment by mislav** [comment]
> The problem for me was that `will_paginate` in the view is being passed an un-paginated collection

I think everyone who encountered this issue has accidentally passed an un-paginated collection to `will_paginate`.
