### ISSUE TITLE
Define not page but record where pagination should start

### ISSUE THREAD

**Issue by emmanuelmillionaer** [mislav/will_paginate#416]
Lets suppose i have a model `records` that is sort by `created_at` and the client has the records until a specific record with the id `77`. Now would it be possible to define for example:

      Records.paginate(:page => params[:record_id], :per_page => 30)                                                                   

Thanks!

**Comment by mislav** [comment]
Sorry for the late reply! This is not easily done with will_paginate. I guess you would have to first fetch the record, do some math to determine which numeric page does it fall into, then fetch that page. I hope you found some workaround!
