### ISSUE TITLE
Camel-cased ActiveRecord objects create invalid SQL on total_entries() call

### ISSUE THREAD

**Issue by james4765** [mislav/will_paginate#417]
When calling total_entries() on an ActiveRecord search result that is camel cased, it generates invalid SQL.

For example, the ActiveRecord class 'GuiTest' generates the following SQL that fails:

`SELECT COUNT(*) AS count_all, guitests.id AS guitests_id FROM gui_tests  GROUP BY guitests.id`

The database name, per the Rails default, is 'gui_tests'.

**Comment by mislav** [comment]
If the auto-generated COUNT query is incorrect, then it's an Active Record problem. You can work around it by passing an explicit count you perform yourself via `:total_entries`. See https://github.com/mislav/will_paginate/blob/67e11dce90a75d98d184e4bcc1120457e58b477b/lib/will_paginate/active_record.rb#L196-L199
