### ISSUE TITLE
infinite scrolling

### ISSUE THREAD

**Issue by wendy0402** [mislav/will_paginate#419]
Hi, I am just curious. Is there any feature to use infinite scrolling in will_paginate? I know this project is about pagination, but will it be cool? how about we make a feature about it? is it good?

**Comment by sungwoncho** [comment]
I think it's a good idea, but you can write a simple jquery to talk to the will_paginate backend to achieve this.

**Comment by mliyanagamage** [comment]
If your interested in infinite scrolling, there's a tutorial [here](http://www.sitepoint.com/infinite-scrolling-rails-basics/) which shows how to adapt this gem to use infinite scrolling.

**Comment by wendy0402** [comment]
thank you about the tutorial, but somehow it will be nice to make it, but
because it's really simple, it's make sense to just write it manually,
thanks

On Thu, Mar 19, 2015 at 11:37 AM, Migara Aparekka Liyanagamage <
notifications@github.com> wrote:

> If your interested in infinite scrolling, there's a tutorial here
> <http://www.sitepoint.com/infinite-scrolling-rails-basics/> which shows
> how to adapt this gem to use infinite scrolling.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mislav/will_paginate/issues/419#issuecomment-83319295>
> .
>



-- 
*Wendy Kurniawan Soesanto*
Software Engineer
e: wendy.kurniawan@veritrans.co.id

Veritrans Indonesia (PT. Midtrans)
MidPlaza 2, 24th Floor
Jl. Jend. Sudirman Kav. 10-11
Jakarta Pusat 10220
p:  +62.21.573.6789
*www.veritrans.co.id <http://www.veritrans.co.id/>*

**Comment by mislav** [comment]
It's a nice feature when implemented correctly, but it's out of scope for this library. I hope you had fun implementing this since you last commented!
