### ISSUE TITLE
Duplicate entry and remove an other

### ISSUE THREAD

**Issue by spuyet** [mislav/will_paginate#420]
Hello,

A little problem appears in a particular case:

This is my original query:
```ruby
> Event.where("date_end >= ?", DateTime.now).order('date_start ASC').map(&:id)
 => [25, 18, 17, 26, 28, 2, 19, 20, 21, 27, 24]
```
When i have modified my query for adding pagination, the result is wrong:

```ruby
> Event.where("date_end >= ?", DateTime.now).order('date_start ASC').paginate(page: 1, per_page: 5).map(&:id)
 => [25, 18, 17, 26, 2]
```

The result for the next page:

```ruby
> Event.where("date_end >= ?", DateTime.now).order('date_start ASC').paginate(page: 2, per_page: 5).map(&:id)
 => [2, 19, 20, 21, 27]
```
As you can see, the entry '2' is duplicated on the first and second page while the entry '28' disappeared.

**Comment by mislav** [comment]
Thanks @BenjaminDigeon!
