### ISSUE TITLE
Crash with non integer page

### ISSUE THREAD

**Issue by brauliobo** [mislav/will_paginate#425]
```
  invalid value for Integer(): "3index.php"
  vendor/plugins/will_paginate/lib/will_paginate/page_number.rb:16:in `initialize'
```

**Comment by dignoe** [comment]
Hey @mislav, I'm still seeing these errors coming through via Rollbar. You mentioned above that will_paginate should throw a `WillPaginate::InvalidPage` error, but I'm not seeing that. I'm getting `ArgumentError: invalid value for Integer(): "10(('.,."` for the URL `https://www.cardgnome.com/blog?page=10((%27.,.`. This seems to be happening for any page param that begins with a number but isn't a valid integer (e.g. `10((%27.,.`, `2%22`, `2212.1`, etc.). These are all coming from probing bots, and I'd like them to just be handled as 404s.
