### ISSUE TITLE
blank param values referencing nesting route lead to wrong, malformed routes

### ISSUE THREAD

**Issue by gisborne** [mislav/will_paginate#434]
Assume we're inside another route:

resources :bar do
  resources :foo
end

resources :foo

and we're paginating foo. Then if bar is present in params, we wind up generating bar_foos type routes. If our route includes ?bar=&… we wind up with a route that looks like /bar//foo/?page= which is wrong two different ways.

I think the pagination needs to be able to receive a route generator as an argument. I'll see about putting together a pull request.

**Comment by mislav** [comment]
Thanks for reporting, but closing due to not having further reports of this and no PR.
