### ISSUE TITLE
Next/Prev links are inefficient

### ISSUE THREAD

**Issue by gisborne** [mislav/will_paginate#435]
The current method of generating next and prev links is inefficient. See:

http://use-the-index-luke.com/sql/partial-results/fetch-next-page

We should support next and previous links by gathering records before the first entry on the page or after the last entry on the page, as discussed in that article.

Noting that prev is a bit more of a fiddle, we should at least start with supporting efficient next links.

**Comment by mislav** [comment]
Thanks for the suggestion! It's a valid suggestion, and I agree that our current style of pagination is slow for some databases, but would require a complete rewrite of this library as it's an entirely different approach. To have this style of pagination queries, you should use another library.

Closing as wontfix
