### ISSUE TITLE
ActiveRecord paginate always returns empty results

### ISSUE THREAD

**Issue by winstonquock** [mislav/will_paginate#441]
With ActiveRecord 2.3 / JRuby 1.7 and will_paginate 2.3.16, the AR paginate mixin method doesn't work as expected. Always returns empty results. But regular array based pagination (e.g. User.find(:all).:paginate() works.

```
>> users = User.paginate(:all, :page => 1, :per_page => 10)
=> []
# query performed, verified correct: select * from (SELECT * FROM "USERS" WHERE ("USERS".is_deleted = 0 or "USERS".is_deleted is NULL)  ORDER BY id) where rownum <= 10
>> users.size
=> 0
>> users.total_entries
=> 0
```

**Comment by mislav** [comment]
Sorry, but that looks like an ActiveRecord bug with the query limit option. Anyway, I'm pretty sure you solved this in the meantime. Closing as stale.
