### ISSUE TITLE
Data-attributes

### ISSUE THREAD

**Issue by shilpi230** [mislav/will_paginate#442]
Hi. I'd like to know how to have the data-push attribute in pagination link. I'm using Wiselinks gem. Thanks!

**Comment by rishijain** [comment]
If you pass options like this: ``` will_paginate @posts, {'data-length' => 20}```, it would set this options to ```<div class='pagination'>```.

If you want to set option to all the pagination links, then you can do something very similar to what is shown in the gist here https://gist.github.com/jeroenr/3142686.

**Comment by WaKeMaTTa** [comment]
We need a better way. =(

**Comment by mislav** [comment]
Sorry for the late reply. Indeed, the workaround that @rishijain linked to is the correct one.
