### ISSUE TITLE
Pagination links point to the root path

### ISSUE THREAD

**Issue by snitko** [mislav/will_paginate#444]
I have a `Question` resource with the `QuestionsController` and standart routes.

For some reason, `#will_paginate` generates links that point to the `root_path` instead of `questions_path` - that is even if I explicitly set `params: { controller: 'questions', action: 'index' }`

Any ideas what this might be?

**Comment by marcosfelipe** [comment]
Same issue. I'm the rendering the pagination from an update action and the links are pointing to edit path (/resources/:id?page=1) and not to index path (/resources?page=1). So I have to set explicity the controller and the action parameters.

**Comment by snitko** [comment]
I would like to point out that, interestingly, setting controller and action explicitly still solve the issue for me.

**Comment by mislav** [comment]
Setting controller/action explicitly is the correct workaround when the route generation is ambiguous.
