### ISSUE TITLE
How to avoid SELECT COUNT ?

### ISSUE THREAD

**Issue by Davidslv** [mislav/will_paginate#447]
Hey guys, we the following code for pagination, which is pretty much trivial.

```ruby
User.paginate(page: page, per_page: limit).order(id: :desc)
```

The problem is that it executes a second query to count the number of records in the table, and that's a very expensive operation, especially in a very big table (which is the case), is there any option to avoid doing that extra count? It's not necessary for us to have it.

```
D, [2015-07-30T13:34:11.370298 #3] DEBUG -- :   User Load (4.0ms)  SELECT  "users".* FROM "users" INNER JOIN "table_x" ...
D, [2015-07-30T13:34:11.407058 #3] DEBUG -- :    (34.9ms)  SELECT COUNT(*) FROM "users" INNER JOIN ...
```

Thank you

**Comment by wilg** [comment]
Curious about this as well!

Postgres counting is slow: 
- http://stackoverflow.com/questions/14570488/how-do-i-speed-up-counting-rows-in-a-postgresql-table
- http://chrisdone.com/posts/postgresql-pagination

Would be great if will_paginate supported a mode where instead of using LIMIT/OFFSET it just let did `where("whatever_i_am_sorting_by > ?", last_value_for_this_column_on_the_previous_page)`

**Comment by Davidslv** [comment]
We solved this with using offset

```ruby
.offset((page - 1) * limit).limit(limit)
```

**Comment by epinault** [comment]
I don t see this when I use 
Model.page(params[:page]).order(:id)

**Comment by mislav** [comment]
will_paginate needs to perform the COUNT to know how many pages in total there are so it can generate pagination links. That's the sole purpose why the library was created.

Now, I understand that some COUNTs are slow. Yours, for instance, could maybe be replaced with a simple `:total_entries => User.count` parameter to `paginate()`, avoiding the expensive `INNER JOIN` when counting the users.

**Comment by rgaufman** [comment]
Kaminari has a mode without_count for those that just need simple "next page", "previous page" buttons: https://stackoverflow.com/questions/13284860/kaminari-without-count

**Comment by mislav** [comment]
https://github.com/mislav/will_paginate/wiki#limitations
