### ISSUE TITLE
Navigating pages makes the entire site disappear.

### ISSUE THREAD

**Issue by Arcrammer** [mislav/will_paginate#451]
When I click the links to go between the different sets of data the entire viewport goes empty. It becomes pure white. If I refresh the page, though, I'll see what I need. Why is this happened and what can I do to stop it?

**Comment by mislav** [comment]
Sorry for the late reply. If a refresh fixes it, then it sounds like a JavaScript error. Since will_paginate plugin doesn't do JavaScript out-of-the-box, then it must be some code in your application or a plugin that ajaxifies pagination links or something similar.

**Comment by Arcrammer** [comment]
I'd figured out the problem was a script I was using which used the `document.write()` method to write a script to the page at the very last minute. This was breaking the pagination so I removed that call to `document.write()` and replaced it with a hard coded HTML script element:

<img width="958" alt="screen shot 2015-09-13 at 10 07 35" src="https://cloud.githubusercontent.com/assets/8358956/9837034/675d191e-59ff-11e5-8b54-3f83600b3176.png">

You can look more closely <a href="https://github.com/Arcrammer/Tara-Crammer-Designs/commit/682570622d164039739e29604bdf20c3cf139aff">over here</a> for the diff if you're really interested.

**Comment by mislav** [comment]
Thanks for the update!
