### ISSUE TITLE
[question] How to unset per_page and return all results...

### ISSUE THREAD

**Issue by abitdodgy** [mislav/will_paginate#454]
In other words, set per_page to max count of model. This is useful if you have an index action that uses multiple formats (documents index in pdf, html, json, etc). In the HTML view I want to paginate as usual, but I want to download a list of documents in PDF, and for that I would like all records to be included without pagination. Is this possible? It's easy to create a different controller action that does not apply pagination, but is there an elegant way to return all records?

**Comment by rishijain** [comment]
How about using conditional statements under respond_to. So you won't need to have multiple actions.
```
respond_to do |format|
  format.html do
    #collect objects as per pagination 
  end
  format.pdf do
    #collect all objects 
  end

**Comment by abitdodgy** [comment]
@rishijain That's what I ended up doing...

```ruby
    respond_to do |format|
      format.html {
        @documents = @documents.page(params[:page])
      }

      format.pdf {
        render_pdf @project
      }

      format.zip {
        stream_zip @project, @documents
      }
```
