### ISSUE TITLE
Is it possible to paginate with letters?

### ISSUE THREAD

**Issue by OlegPasko** [mislav/will_paginate#458]
I have project wilth cities listing and it may be very useful to have something like:
'aa - am - b - c - e - k'... like in books/dictionaries? :)

Is it any easy way to do that?

**Comment by rishijain** [comment]
I did not completely get what you want. I am assuming that you want to change the text of the links to a,b,c,d.... I think my comments in  https://github.com/mislav/will_paginate/issues/459 would help you overwrite your links.

**Comment by mislav** [comment]
@OlegPasko No, this is not supported. See https://github.com/mislav/will_paginate/issues/319
