### ISSUE TITLE
Removing link to last page.

### ISSUE THREAD

**Issue by edsanz** [mislav/will_paginate#461]
I have an app with millions of pages.  We need to remove the link to the last page.  You know the links between the ... and Next link.  So instead of seeing Previous 1-2-3-4-5-6-7-8-9 ... 110,000,000 Next.  I want the user to see Previous 1-2-3-4-5-6-7-8-9-10 Next.  If the user wants to navigate to the last page he should click on Next a million times.  This is done for performance reasons.  This is similar to the way Google's pagination works.  If a search has 50 million records in Google they don't give you a link to go to the last and least relevant page.

How can I remove the last link on will_paginate? I already used :outer_window => 0 but that only gets rid of the second to last page link.  Thanks.

**Comment by adrianoresende** [comment]
+1 for remove outer_window

`outer_window: false`

**Comment by mislav** [comment]
I've proposed a solution here: https://github.com/mislav/will_paginate/pull/484#issuecomment-252927444

I doubt that there will be a simple parameter to turn last pages. However, using link renderer it's fairly customizable.
