### ISSUE TITLE
Not compatible with Rails 5.0.0.beta1

### ISSUE THREAD

**Issue by lohqua** [mislav/will_paginate#462]
Are you going to update this gem for Rails 5 compatibility?

Thank you.

**Comment by jonatack** [comment]
I've been maintaining a [Rails 5 version here](https://github.com/jonatack/will_paginate) since last summer.

**Comment by mislav** [comment]
A PR that brings Rails 5 compatibility to will_paginate is very welcome; thanks!

**Comment by jonatack** [comment]
Will do tomorrow.
