### ISSUE TITLE
Can we control maximum number of pagination links that can be shown?

### ISSUE THREAD

**Issue by sahil290791** [mislav/will_paginate#471]
Can we have an additional feature or option which allows us to control maximum number of pagination links that are shown on page. 
As in few website designs where the layout is centered the designer gets very less space to add pagination and once we have more than 20 pages it gets difficult to show all the pagination links.
In the current pagination gem it shows 14 links (including prev, next and `...` links).

![pagination](https://cloud.githubusercontent.com/assets/7287280/13282910/4442bb12-db11-11e5-8109-e9b636230c0a.png)

**Comment by msarit** [comment]
+1

**Comment by mislav** [comment]
You can reduce the total number of pagination links rendered by changing the `:outer_window` option to `will_paginate` view helper: https://github.com/mislav/will_paginate/wiki/API-documentation
