### ISSUE TITLE
Rails 5 deprecation

### ISSUE THREAD

**Issue by connorshea** [mislav/will_paginate#472]
I'm getting this issue, Rails 5.0.0 master, will_paginate 3.1.0:
```
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from status_code_with_paginate at /Users/connor/.rvm/gems/ruby-2.3.0/gems/will_paginate-3.1.0/lib/will_paginate/railtie.rb:49)
```

Better Errors had/has a similar issue, if you want an example fix you can check out [this PR](https://github.com/charliesome/better_errors/pull/335).

**Comment by zyxan** [comment]
+1

**Comment by emilslv** [comment]
Same problem with same gems as zyxan
