### ISSUE TITLE
Limiting number of pages in links using will_paginate 

### ISSUE THREAD

**Issue by poombavai** [mislav/will_paginate#476]
Hi.. I am using the following gems

gem 'will_paginate', '~> 3.0.6'
gem 'will_paginate-bootstrap'

:inner_window and outer_window properties doesnot showing me any changes in my page.. I have tried like,

my views,

<%= will_paginate @issue, page_links: true, inner_window: 2, outer_window: 1 %>

my controller,

@issue = Issue.all.paginate(page: params[:page], per_page: 5).order("issue_slip_no DESC")
..
How should I correct it?

**Comment by peter1403** [comment]
<%= will_paginate(@collection), :inner_window => 2, :outer_window 1 %> 

if your code is the same as the one you pasted above, it may just be a syntax error, copy this one(changing the variables ofcourse)

**Comment by mislav** [comment]
Hi, sorry this issue didn't get any attention. I hope you solved your problem by now using the parameters available to the `will_paginate` helper method.
