### ISSUE TITLE
will_paginate causing blank page

### ISSUE THREAD

**Issue by chaddpaul** [mislav/will_paginate#477]
I am working on a search engine site that uses sunspot solr. I just recently started experiencing issues with using the will_paginate buttons to move from one search page to the next. Originally are page would display the first 16 elements and then if you clicked next will_paginate would call for the next 16 class to display and so on. The issue we are facing now is that when I click the next button it calls the appropriate next page to be displayed but the page is returned as a blank page. IF I refresh the page the page will generate with the appropriate classes and views which proves that will_paginate is calling the right link.

I should also add if you use the url parameters to view specific pages all the pages will display as they should so only when switching pages using the pagination buttons is the error in displaying the page being caused.

Any help would be hugely Appreciated

**Comment by mislav** [comment]
Sorry, but this sounds more like an application problem than a will_paginate problem! will_paginate doesn't actually render your whole web page. So, if the whole page is blank, then something is wrong with your app. Check your application log for any exceptions or information why the page is blank.
