### ISSUE TITLE
params[:page] carry-over with 2nd pagination

### ISSUE THREAD

**Issue by emclab** [mislav/will_paginate#479]
In our app, there is a list of purchase orders which have order items. Both of the listing use will_paginate. Here is the code for purchase orders:

@orders = @orders.page(params[:page]).per_page(30)

Here is the code for order items:

@order_items = @order_items.page(params[:page]).per_page(30)

As the code shows, both of them reply on params[:page] to start with. The problem is that when a user is on, for example, 2nd page of the purchase orders, the params[:page] is set to 2. Then the order items list will start with params[:page] = 2 instead of page 1. This causes no-listing of page 1 for order items. Is there a nice way to solve this problem caused by params[:page] carry-over?

**Comment by joaozig** [comment]
Have you tried to change `:param_name` on order_items helper?
something like: `<%= will_paginate @order_items, :param_name => :item_page %>`

I tried to reproduce this scenario here and I think it might work for you

**Comment by mislav** [comment]
@joaozig suggestion is probably what you need! You shouldn't have 2 paginations on the same page with the same `param_name` (default: `page`).
