### ISSUE TITLE
will_paginate and mongoid

### ISSUE THREAD

**Issue by eucandre** [mislav/will_paginate#480]
i read the tutorial will_paginate_mongoid and will_paginate. The result:

undefined method `total_pages' for #Mongoid::Criteria:0x007f7c097b9030

And I can not find anything about it will_paginate and Mongoid.

**Comment by mislav** [comment]
Sorry for the late reply. Please see https://github.com/mislav/will_paginate/issues/561#issuecomment-1410077037
