### ISSUE TITLE
Simple-search

### ISSUE THREAD

**Issue by paulomcnally** [mislav/will_paginate#481]
This code work on rails 4x

```
def self.search(search, page)
    self.where("lower(name) LIKE '%#{search.downcase}%'")
    .paginate(:page => page, :per_page => 10).order('name ASC')
end
```

https://github.com/mislav/will_paginate/wiki/Simple-search

**Comment by cosmoschen94** [comment]
I was having this issue when trying to use :conditions in the wiki. This works! Thx!
