### ISSUE TITLE
Pagination links breaks when paginated with search params in Rails 5

### ISSUE THREAD

**Issue by rahulvn** [mislav/will_paginate#486]
I was working on ruby 2.3.0 - rails 5.0.0.rc1 - will_paginate 3.1.

Pagination link breaks when there is a search param in the URL.

**Comment by jesseiqmi** [comment]
@rahulvn Same thing here - found the following to address this https://github.com/jonatack/will_paginate

Giving it a try now myself to see if this works until this can be addressed here.

**Comment by jesseiqmi** [comment]
@rahulvn nix that.  I got a whole bunch of other errors.

Did you find a way through this yourself?  Here's another ticket from Ransack that looks familiar as well: https://github.com/activerecord-hackery/ransack/issues/687

**Comment by rahulvn** [comment]
@jesseiqmi I have fixed it with this patch: https://github.com/mislav/will_paginate/pull/483

**Comment by jesseiqmi** [comment]
@rahulvn thanks - I did the same thing with an earlier PR found at https://github.com/mislav/will_paginate/pull/469/commits/e11cae7b2d9801719b9baa5db1588793809b8c7e (less overall changes to solve my immediate issue).

Cheers

**Comment by rahulvn** [comment]
Great :+1

**Comment by jonatack** [comment]
Ransack master has been working with Rails 5 since a year and a half now:

```ruby
gem 'ransack', github: 'activerecord-hackery/ransack'
```

Will cut a new official Ransack release very soon, but Ransack master is available.


P.S. as mentioned near the top of the Ransack README, if you are using will_paginate, for now you'll need to use my version:

```ruby
gem 'will_paginate', github: 'jonatack/will_paginate'
```

**Comment by jonatack** [comment]
Apologies, posted in the wrong page 😄. Cheers.
