### ISSUE TITLE
When using :params option, flush all other params

### ISSUE THREAD

**Issue by nladd** [mislav/will_paginate#489]
I'd like to suggest a change to how the :params option works. Currently, when the params option is used, the passed parameters are added to the current url. I'd suggest, that instead, only the passed parameters are used, thus flushing out the current url params. 

E.g. if the page with my pagination links has a url of http://www.example.com?foo=bar and I call will_paginate with the option :params => { baz: "foo" }, then the generated pagination links will look like 
http://www.example.com?foo=bar&baz=foo. 

I'd suggest that only the passed parameters be used in the generated pagination links to allow users to flush other parameters off the url if they aren't wanted so that in the above example the generated pagination links would look like, http://www.example.com?baz=foo

To accomplish this, in my app I have monkey patched WillPaginate::ActionView::LinkRenderer#merge_get_params to be:

````
def merge_get_params(url_params)
  return {} if @options[:params]
  if @template.respond_to? :request and @template.request and @template.request.get?
    symbolized_update(url_params, @template.params)
  end
  url_params
end
````

**Comment by mislav** [comment]
Your suggestion is not bad, but I'm afraid I can't make that change for backwards compatibility reasons. Too many people now rely on the fact that `:params` adds extra parameters but keeps existing ones.

You can _subclass_ `WillPaginate::ActionView::LinkRenderer` (avoiding having to monkeypatch it directly) and use the new renderer (via `:renderer => MyClass` option) in places where you want to completely replace parameters.

**Comment by nladd** [comment]
Ok. I understand and makes sense. Thanks for the response and I'll look into you suggestion to help my specific situation
