### ISSUE TITLE
error when paging through arrays 

### ISSUE THREAD

**Issue by vinnyoodles** [mislav/will_paginate#493]
undefined method `total_pages' for #<Array:0x007f42fd1e29d0>

```
        <div class="pagination">
          <div class="page_info">
            <%= page_entries_info @array %>
          </div>
          <%= will_paginate @array, :page_links => false %>
        </div>
```

**Comment by mislav** [comment]
You can't show pagination links for a static array directly. You can, however, first paginate it:

```rb
@paginated_array = @array.paginate(:page => 1, :per_page => 30)
```

Now you can pass `@paginated_array` to `page_entries_info()` and `will_paginate()`.
