### ISSUE TITLE
unsupported parameters: :conditions

### ISSUE THREAD

**Issue by arconale** [mislav/will_paginate#500]
hello,

i'm facing an issue with will_paginate.
 
i used paginate :per_page => per_page, :page => page, 
  			:conditions => conditions, :order => 'title'
and i got this error 
unsupported parameters: :conditions
Thanks

**Comment by mislav** [comment]
@arconale Hello, `:conditions` is not supported in newer versions of Active Record. Try:

```rb
User.where(conditions).order('title').per_page(per_page).page(page)
```

**Comment by jake-mia** [comment]
Hi Mislav, great product.  Thank you.  I am having issues with conditions as well.  First i noticed in your example above that you did not use the .pagination method.  For me, i am using the pagination method and it returns the first page ok, but when I go to any of the #2, #3, ..n pages it is blank.  
Works fine if i remove the ".where(conditions)".  Any advice greatly appreciated.  thanks!
conditions = 'zip like ? AND lower(city) like ? AND acct_role = ?', "#{var}%","%#{params[:city]}%","#{params[:acct_role]}"
 
@results = User.where(conditions).paginate(:page => params[:page], :per_page => 2)

**Comment by jake-mia** [comment]
Rails 5.0.1.  thanks,

**Comment by jake-mia** [comment]
ahh... just needed a comma in my form.  The :method => get was being ignored.  This is resolved.  thanks.
