### ISSUE TITLE
Add HTML attributes to generated links (pages)

### ISSUE THREAD

**Issue by ezilocchi** [mislav/will_paginate#512]
I'm trying to get `will_paginate` working with AJAX on rails. So I need to set the `data-remote=true` attribute on each link, like `<a data-remote=true>`. So it would be great if we were able to set HTML5 attributes to the generated links. Probably something like:
```ruby
will_paginate @models, links: {'data-my-attr': 'some value'}
```

so it will generate
```html
<div class="pagination">
  ...
  <a data-my-attr="some value">...</a>
  ...
</div>
```

**Comment by mislav** [comment]
https://github.com/mislav/will_paginate/wiki/Link-renderer
