### ISSUE TITLE
Using 'order' with paginate has error

### ISSUE THREAD

**Issue by franhsieh** [mislav/will_paginate#513]
Hi all,

I had question about using paginate with order.
When I do below in controller
'Post.includes(xxx).order("status_id").paginate(page: params[:page], :per_page => 15)'
I cannot get correct result as expected. There are repeated items in page 1 and page 2. 

I check the result of using order only and without paginate in controller, I got correct sequence, ID starting from 29, 3, 4, 5, 6, 30, 24, 25...
But if phenomenon occurred, I got wrong sequence, ID starting from 14, 2, 3, 6, 30... Obviously it had wrong result, so there are repeated items.
I also did other order, they all occurred same phenomenon.
Don't know is there any one has familiar phenomenon with me.
my environment is Rails 4.2.6 + postgresql 9.4.4.1 + Using will_paginate 3.1.5, running on Mac development.

**Comment by jultra** [comment]
I first call `paginate` before `order` and it works for me.

**Comment by rsheldiii** [comment]
I'm having a lot of issues with complex queries and this gem. I am trying to show a list of projects, with 'favorited' projects at the top, which requires a tricky sort. Executing this query:

```
user
  .projects
  .includes(:favorites)
  .references(:favorites)
  .order("CASE WHEN favorites.user_id=#{user.id} THEN 1 ELSE 2 END ASC", "coalesce(projects.name, 'Untitled Project') ASC")
  .map { |p| { name: p.name, favorite: p.favorited_by?(user) } }[0...6]
```

produces this output:
 
```
[
  {:name=>"Project 5", :favorite=>true},
  {:name=>"Project 6", :favorite=>true},
  {:name=>"Project 7", :favorite=>true},
  {:name=>"Project 8", :favorite=>true},
  {:name=>"Project 9", :favorite=>true},
  {:name=>"Project 1", :favorite=>false}
]
```

but adding the pagination gem anywhere in the flow:

```
user
  .projects
  .includes(:favorites)
  .references(:favorites)
  .order("CASE WHEN favorites.user_id=#{user.id} THEN 1 ELSE 2 END ASC", "coalesce(projects.name, 'Untitled Project') ASC")
  .paginate({page: 1}) # only difference
  .map { |p| { name: p.name, favorite: p.favorited_by?(user) } }[0...6]
```

produces:

```
[
  {:name=>"Project 5", :favorite=>true},
  {:name=>"Project 6", :favorite=>true},
  {:name=>"Project 1", :favorite=>false},
  {:name=>"Project 2", :favorite=>false},
  {:name=>"Project 3", :favorite=>false},
  {:name=>"Project 4", :favorite=>false}
]
```

does anyone have any ideas?

**Comment by crivotz** [comment]
same situation, move the order doesn't solve the problem

**Comment by h8rry** [comment]
same problem

**Comment by fabriziobertoglio1987** [comment]
```ruby
Location
   .with_posts
   .newest
   .newest_cameras
   .newest_posts
   .paginate(page: 1, per_page: 1)
   .count
=> 3
```
this is my model 
```ruby
class Location < ApplicationRecord
  has_many :cameras
  has_many :posts, through: :cameras
  has_one :forecast
  before_save :set_last_camera_at
  scope :with_posts, -> { includes(cameras: :posts).where(cameras: { posts: { flagged: false }}) }
  scope :newest, -> { order(last_camera_at: :desc) }
  scope :newest_cameras, -> { order('cameras.last_post_at DESC') }
  scope :newest_posts, -> { order('posts.created_at DESC') }
end
```

seems that `paginate` does not work with nested conditional `includes`

**Comment by mislav** [comment]
Hi thank you all for reporting problems. This library only extends Active Record and relies on it to handle making the paginated query. That doesn't always work, especially with `includes` and `group` statements. See https://github.com/mislav/will_paginate/wiki#limitations

Closing this as something that we likely won't handle in this library.
