### ISSUE TITLE
Error returning records by page

### ISSUE THREAD

**Issue by Xosmond** [mislav/will_paginate#517]
I have a problem with will_paginate, when i do this:
`Movement.paginate(:page => params[:page])`

All is ok, but when i specify number of pages:

`Movement.paginate(:page => params[:page], per_page: 12)`

The first page is blank and the second page has the first record. Do you know why this happens?

**Comment by DrobyshevAlex** [comment]
I have 2282 pages but If opened any page i got then will_paginate show only 2280 

> 1 2 3 4 5 6 7 8 9 … 2279 2280

if i write to url ?page=2281
i still have 

> 1 2 … 2272 2273 2274 2275 2276 2277 2278 2279 2280

but i have correct records on page

if i write to url ?page=2282 then i have 

> 1 2 … 2274 2275 2276 2277 2278 2279 2280 2281 2282

i have a correct count pages

UsersConteroller

`@models = User.includes(:role, :phone).references(:role, :phone).order('users.id').paginate :page => params[:page]`


index.html.erb

`<%= will_paginate @models %>`
