### ISSUE TITLE
Default view labels broken from 3.1.3

### ISSUE THREAD

**Issue by richhollis** [mislav/will_paginate#521]
Hi

First, thanks for a great project!

I recently noticed that the previous and next labels in one of my projects changed from their arrows and correct labels to saying "Previous Label" and "Next Label" (the symbols).

Tracing back, I found that the problem is introduced in 3.1.3. There are some I18n changes (c8361be08f1d34712e98509dc2bbfccb057711a1 and a3df0ae60ec0e0e4e0a3f3fd9327879a13427648) in there so I wonder if anything stands out to you.

If I manually add the labels to my en.yml file then they do start working again, so it's like will_paginate just can't locate it's own default labels.

This is with a Rails 3.2.22.x project in case that's a factor. I'll revert to 3.1.2 for the time being.

Let me know if I can help at all.

Thanks!

**Comment by richhollis** [comment]
I'm going to close this issue because IMHO the better fix is to upgrade to Rails 4+. This issue is not present in 4.0.

**Comment by toncid** [comment]
This is reproducible in Rails v4.2.7, so it's not caused by Rails.

**Comment by richhollis** [comment]
That's strange! I've just tested it again in 4.x (4.0.13 effective) and it is working OK with the latest version 3.1.5. I will be upgrading to 4.2 shortly so I will see what happens when I get there and report back.

**Comment by CharlieIGG** [comment]
Having the exact same issue using Rails 5.0.4
