### ISSUE TITLE
Make it compatible with Ruby 2.4.0

### ISSUE THREAD

**Issue by TroySK** [mislav/will_paginate#523]
Ruby 2.4.0 has deprecated Fixnum for Integer. Making the change will make logs cleaner save millions of bytes!

**Comment by markets** [comment]
@TroySK There are a couple of related PR to fix this issue:

- https://github.com/mislav/will_paginate/pull/522
- https://github.com/mislav/will_paginate/pull/515

**Comment by TroySK** [comment]
@markets Cool! Hope to see one of them incorporated in the next release 😄 .

**Comment by FireFart** [comment]
@mislav any chance you can have a look at this change?

**Comment by marksiemers** [comment]
Here is a new PR that passes all the build tests: https://github.com/mislav/will_paginate/pull/538
