### ISSUE TITLE
undefined method `total_pages'  for association

### ISSUE THREAD

**Issue by niharika88** [mislav/will_paginate#527]
I am getting 
undefined method `total_pages' for #<Transaction::ActiveRecord_Associations_CollectionProxy 
if I,am trying to paginate a resource  which current_user.transactions.
While using global variable @ transactions works fine .

**Comment by hubertjakubiak** [comment]
Could you provide more details how to reproduce this error? I would like to help you with it.

**Comment by niharika88** [comment]
When I try pagination for associated Entities I get the above error.
Suppose there is a model name transactions.
and a model User which has many transacions now I want to paginate User.transactions rather that transactions.all.
I am not sure how to accomplish this

**Comment by hubertjakubiak** [comment]
I created some simple app to reproduce your error. I have two models `User` and `Order`. As you can guess user `has_many` orders and each order `belongs_to` to user.

```
class User < ApplicationRecord
  has_many :orders
end
```

```
class Order < ApplicationRecord
  belongs_to :user
end
```

```
def show
  @orders = @user.orders.paginate(page: params[:page], per_page: 3)
end
```

```
<% @orders.each do |order| %>
  <p><%= order.name %></p>
<% end %>
<%= will_paginate @orders %>
```

I can see you error when `@orders` is just defined to `@user.orders`. Are you sure that you not forgot to add `paginate` method to collection? If not, could you provide your code?

**Comment by Pedro5000** [comment]
Hi, 
I'm encountering a similar issue with this:

```
class User < ApplicationRecord
  has_many :orders
end
```

```
class Reviews < ApplicationRecord
  belongs_to :reviews
end
```
```
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])
    @reviews_count = @user.reviews.count
    @reviews = @user.reviews.paginate(page: params[:page], per_page: 1)
  end
end
```
```
# users/show.html.erb
      <% if @reviews_count > 0 %>
        <h2 class="mb-4">Published <%= 'Review'.pluralize(@reviews_count) %></h2>
        <% @reviews.each do |review| %>
          <%= render partial: 'reviews/review', object: review %>
        <% end %>
      <%= will_paginate @reviews %>
      <% end %>
```
I get this error:
`undefined method `total_pages' for #<Review::ActiveRecord_AssociationRelation:0x00007fabb5847570>`

The pagination works (showing only 1) when I don't include  `<%= will_paginate @reviews %>` in my view.

**Comment by mislav** [comment]
@hubertjakubiak Thank you for trying to help!

Others: this error most definitely happens when you forgot to `paginate` a resource. https://github.com/mislav/will_paginate/issues/411#issuecomment-835809901
