### ISSUE TITLE
We need a real tutorial to modify css and Link renderer...

### ISSUE THREAD

**Issue by bebeun** [mislav/will_paginate#529]
Thank U :-) )

**Comment by javierguajardo** [comment]
@bebeun I haven't found any tutorials that explain how to modify the `link renderer`. But I've used this gem in the past which integrates a `Bootstrap pagination component` with **will_paginate**.

https://github.com/bootstrap-ruby/will_paginate-bootstrap

Hope it helps.

**Comment by alex-tazy** [comment]
Like this https://github.com/mislav/will_paginate/wiki/Link-renderer ?

**Comment by mislav** [comment]
There is no real tutorial, just rough pointers: https://github.com/mislav/will_paginate/wiki/Link-renderer

You will have to read parts of will_paginate code to achieve what you need. There is no way around it, other than writing your own view logic to render pagination links from scratch.
