### ISSUE TITLE
Use will_paginate in Rails API

### ISSUE THREAD

**Issue by simlw** [mislav/will_paginate#532]
I have a Rails api server and I use React.js as the view instead of erb or other templates, so I just want a JSON data which contains current_page, total_pages. Does it support that?

**Comment by GiancarlosIO** [comment]
maybe you can get that info like:
`per_page = 12`
`@max_pages = Product.count % per_page > 0 ? (Product.count / 12) + 1 : Product.count`
`@current_page = params[:page]`

or are you looking for a specific requirement?

**Comment by simlw** [comment]
I found that the active record results has **total_entries**, I used them and solved my problem. 
`
page = 2
per_page = 12
products = Product.all.paginate(page: page, per_page: per_page)
total_pages = products.total_entries / per_page
`
In above code, total_pages is what I want.  Thank you very much for your replay.
