### ISSUE TITLE
warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by denisoster** [mislav/will_paginate#539]
**Rails 5.1.1
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]**
`/gems/will_paginate-.1.5/lib/will_paginate/view_helpers/link_renderer.rb:27: warning: constant
::Fixnum is deprecated
/gems/will_paginate-.1.5/lib/will_paginate/view_helpers/link_renderer.rb:91: warning: constant ::Fixnum is deprecated`

**Comment by rhombl4** [comment]
Duplicate #523, #528, #538

**Comment by mislav** [comment]
Thanks @rhombl4!
