### ISSUE TITLE
Validation of params[:page] ?

### ISSUE THREAD

**Issue by adrian282** [mislav/will_paginate#547]
Is a :page parameter validated?

If I change :page to non-numeric value I got the exception. I think that should be treated as `1`

**Comment by mayesgr** [comment]
Our apps, especially our external ones subject to bots and bad actors, are plagued by non-numeric values being used as a "page" value in the URL so we have to validate params[:page] ourselves: convert it to an integer greater than zero or else set it to nil.  Otherwise, it's a 500 error.

**Comment by mislav** [comment]
Duplicate of #271
