### ISSUE TITLE
Upgrade to rails 5.0

### ISSUE THREAD

**Issue by joaoBordalo** [mislav/will_paginate#549]
Hi there,

I'm upgrading an app from rails 4.2.7 to rails 5.0.4

I have done the upgrade according to this guide: [here](https://hashrocket.com/blog/posts/how-to-upgrade-to-rails-5#3-update-rails-binaries-and-configurations).

However, when I try to run the server by:
$rails s -b 0.0.0.0

I get the following error:
$ rails s -b 0.0.0.0
=> Booting Thin
=> Rails 5.0.4 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Exiting
/home/clouduser/newrails5/project-control/config/initializers/will_paginate.rb:15:in `<module:ActionView>': **uninitialized constant WillPaginate::ActionView::LinkRenderer (NameError)**
       from /home/clouduser/newrails5/project-control/config/initializers/will_paginate.rb:2:in `<module:WillPaginate>'
        from /home/clouduser/newrails5/project-control/config/initializers/will_paginate.rb:1:in `<top (required)>'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:648:in `block in load_config_initializer'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:166:in `instrument'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:647:in `load_config_initializer'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:611:in `each'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `run'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:44:in `each'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `call'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/application.rb:352:in `initialize!'
        from /home/clouduser/newrails5/project-control/config/environment.rb:5:in `<top (required)>'
        from /home/clouduser/newrails5/project-control/config.ru:3:in `block in <main>'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
        from /home/clouduser/newrails5/project-control/config.ru:in `new'
        from /home/clouduser/newrails5/project-control/config.ru:in `<main>'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands/server.rb:84:in `app'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands/server.rb:148:in `log_to_stdout'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands/server.rb:102:in `start'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:90:in `block in server'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85:in `server'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
For me it is really strange. It worked on the previous version. Can you help me?
Thank you for your time!

João Bordalo

**Comment by ctl** [comment]
It's very weird. I use Rails 5.1 and everything is ok.

**Comment by joaoBordalo** [comment]
Did you upgrade your app or are you starting a new one? I found how to
solve by paying attention to the files that were changed when I run rails
update command

Em 17/10/2017 12:53 da tarde, "Javinto" <notifications@github.com> escreveu:

**Comment by javinto** [comment]
Interesting… what was your solution in the end?

I upgraded both projects. But i just managed to solve it as you can see in my updated comment.

**Comment by joaoBordalo** [comment]
My desision was to skip modifications and accept new files


Em 17/10/2017 1:15 da tarde, "Javinto" <notifications@github.com> escreveu:

**Comment by javinto** [comment]
Okay, that wat was what I had done for most of the files ;-)

**Comment by mislav** [comment]
Closing as stale

**Comment by rozhok** [comment]
I've stumbled same issue during upgrade from rails 6.0 to 6.1. Looks like 6.1 has more strict autoloading rules so I've had to add `require 'will_paginate/view_helpers/action_view'` to my renderer and it fixed the issue.
