### ISSUE TITLE
Next/previous links are still clickable on first/last page

### ISSUE THREAD

**Issue by kstratis** [mislav/will_paginate#551]
Using Rails 5.1.2 and will_paginate 3.1.6 it seems that even when a user is on the last/first page of the dataset, next and previous links are still clickable and generate an ajax request(using turbolinks). 

<img width="414" alt="disabled_link" src="https://user-images.githubusercontent.com/1859806/29040699-ae8208e0-7bb8-11e7-82b0-4affa132255d.png">

`Next` may look to be disabled but the ajax request goes through nonetheless.

This is a look at Chrome inspector. 

<img width="295" alt="disabled_link_users" src="https://user-images.githubusercontent.com/1859806/29040707-b73a62a2-7bb8-11e7-8a3b-3daff02a09f9.png">

Is this behavior intentional?

EDIT: I've found a workaround to get the behavior I want by setting the following in my css:

```css
.disabled {
  pointer-events: none;
}
```

but it's probably not the proper way to do it.

Any better ideas?

**Comment by ctl** [comment]
I use Rails 5.1 and didn't had same problem ever. Possibly problem isn't in WillPaginate  , but in your WillPaginate theme.

**Comment by kstratis** [comment]
It turns out you are right @ctl.

Indeed, I forgot to mention that I'm also using the [bootstrap-will_paginate](https://github.com/yrgoldteeth/bootstrap-will_paginate) gem. 

If I remove `bootstrap-will_paginate`, the links turn ugly but are no longer clickable as they shouldn't be in the first place. I' m closing the issue here and opening a new one in the [gem's repo](https://github.com/yrgoldteeth/bootstrap-will_paginate/issues/29).

Thanks.
