### ISSUE TITLE
per_page and page being `nil` use defaults instead of not paginating

### ISSUE THREAD

**Issue by xgt001** [mislav/will_paginate#558]
Hi,

Recently faced an issue where the code went like

```
my_model.find.paginate(page: params[:page], per_page: params[:per_page]).order("id DESC")
```
So it happens that one of the API calls had no params[:page] / params[:per_page] set, this resulted in will_paginate using the default of 30.

I wonder if will_paginate should be not paginating if the arguments passed here are explicitly nil instead of using the default values?

Please feel free to close this if this is by design.

Thanks,
Ganesh

**Comment by sudeept-cuelogic** [comment]
Passing `nil` explicitly sounds somewhat ridiculous, if you don't want pagination to appear, don't call `paginate` method instead, problem solved...

All comments will be appreciated... Thanks

**Comment by mislav** [comment]
Pagination methods accept `nil` because that will be the default value of `params[:something]` where a parameter wasn't given. In that case, pagination defaults are applied.

You can apply your own defaults:
```rb
my_model.paginate(per_page: params[:per_page] || 100)
```
