### ISSUE TITLE
Not naturally working with AJAX changes on the page

### ISSUE THREAD

**Issue by AbhijithSpericorn** [mislav/will_paginate#559]
- When using a table that is dynamically changed using AJAX , the will paginate links doesn't update  normally. 

- Please make it more usable with AJAX.

**Comment by MaximPiessen** [comment]
I had a similar problem. I use will_paginate together with Ajax filtering. When the result of one of my filters was less than the 'per_page' parameter of will_paginate, the .pagination div would disappear. From this moment the pagination wouldn't work anymore until you reloaded the page. I found a "hacky" way around this:

In the ajax js.erb file I added: 

  $('.pagination').remove();
  $('body').append("<div class= 'pagination'></div>");
  $('.pagination').replaceWith('<%= j will_paginate(@photos) %>');

So every time my JS-filtering function is called, I delete the pagination div, add it again and populate it with the right data. Hope this helps.

**Comment by ninjarails** [comment]
@MaximPiessen how to pass filters param when will_paginate link is clicked? Need to persist filters options on every pages.

**Comment by MaximPiessen** [comment]
@ninjarails I use a link_to with a param. This param is read by my home action in my pages controller. Next up I send a js response to rerender the content, based on the clicked link and its 'filtering' param. 

Example: 
1) As your filter links you have:
```
<%= link_to root_path(filter: 101), remote: true %>
<%= link_to root_path(filter: 102), remote: true %>
```
2) Your controller action / db query is something like: 
 ```
@content = Class.where(...) if params[:filter] == '101'
@content = Class.where(...) if params[:filter] == '102'
```
3) In your js.erb file, you target pagination div (see previous comment) in which you placed your content and you re-render it with the new content:
```
$('.pagination').remove();
$('body').append("<div class= 'pagination'></div>");
$('.pagination').replaceWith('<%= j will_paginate(@content) %>');
```

**Comment by mislav** [comment]
will_paginate is a server-side library only. Implementing ajax pagination is left as an exercise to the reader.
