### ISSUE TITLE
inner_window, outer_window not working with array of hashes

### ISSUE THREAD

**Issue by willc0de4food** [mislav/will_paginate#564]
I'm having an issue with will_paginate/array where it's displaying the page links for all pages, and completely ignoring the inner_window and outer_window settings. I've tried not specifying them, and setting them to no avail. Is there something I'm missing? I've created a sample app to display the issue that I'm having.
https://wp-array-test.herokuapp.com/
https://github.com/willc0de4food/array_test

Thanks

**Comment by mislav** [comment]
Sorry for the late reply. I can't see where the error is, but it must be something in the setup. The `will_paginate` view method doesn't know where the collection is coming from—it could be from an Active Record model or an array, it's all the same. View parameters such as `:outer_window` should be working with any type of collection and we have tests to prove it. Closing as stale
