### ISSUE TITLE
activesupport-6.0.0.alpha requires ruby version >= 2.4.1

### ISSUE THREAD

**Issue by mukarramali** [mislav/will_paginate#566]
Two of my pipelines get failed on specific versions of ruby and Gemfile.edge:

https://travis-ci.org/mislav/will_paginate/jobs/356826109

This seems because of the bundler version. Bundler 1.16.1(current version) is trying to install activesupport-6.0.0.alpha. Which is not supported in 2.2.4 and 2.3.4

Here is my PR: https://github.com/mislav/will_paginate/pull/565

**Comment by mislav** [comment]
Thank you! This was fixed in the meantime.
