### ISSUE TITLE
ArgumentError: wrong number of arguments (given 0, expected 1)

### ISSUE THREAD

**Issue by cpruitt** [mislav/will_paginate#589]
`will_paginate` conflicts with Rails 5.2.2.1 and 6.0.0.beta2+.

There is already a PR open to fix this (https://github.com/mislav/will_paginate/pull/587), but since this also affects 5.2.2.1 I'm opening the issue as well for the sake of visibility.

will_paginate redefines the private method select_for_count on ActiveRecord with a different number of arguments (the Rails private method accepts zero and will_paginate accepts one) causing an ArgumentError to be raised. Renaming this method prevents Rails from calling the method defined by will_paginate.

See: https://github.com/rails/rails/pull/35361/files

**Comment by mislav** [comment]
Thank you! Fixed in b6fb7b0db9cacb858ab7092a0447ff9db573b9fd
