### ISSUE TITLE
Checking whether records are paginated / will paginate

### ISSUE THREAD

**Issue by Backoo** [mislav/will_paginate#592]
See [this](https://stackoverflow.com/questions/55405480/how-to-check-whether-records-are-paginated), perhaps considering to add a dedicated method for checking whether records are paginated / will paginate.

**Comment by mislav** [comment]
Thank you for linking!

I think checking right now is achievable as per StackOverflow answer. The exact way would probably vary between use-cases. Anyway, this is not something I'm interested in adding to the library now.
