### ISSUE TITLE
FYI: Warning after upgrading this gem to 2.7.0-preview1

### ISSUE THREAD

**Issue by jasnow** [mislav/will_paginate#595]
## Basic Info
Gem Version: 3.1.7
Ruby Version: 2.7.0-preview1
## Issue description
Getting this warning after upgrading to Ruby 2.7.0-preview1:
```
will_paginate-3.1.7/lib/will_paginate/deprecation.rb:35: warning: 
Capturing the given block using Proc.new is deprecated; use `&block` instead
```
## Steps to reproduce
Just upgrade a repo to Ruby 2.7.0-preview1 and then run "rake" command.
Here is a link to other repos working on this issue:

https://github.com/aws/aws-sdk-ruby/issues/2058

**Comment by jasnow** [comment]
Spring Cleaning

**Comment by mislav** [comment]
If this warning is still an issue, why not leave the issue open?

**Comment by jasnow** [comment]
Can't run the tests - tried "rspec" - errors - changed 1 line - "rspec" produces  lots of errors. Can you run the tests/specs?
```
-  config.backtrace_clean_patterns << /view_example_group/
+  config.backtrace_exclusion_patterns << /view_example_group/
```

**Comment by jasnow** [comment]
Upgraded all my repos successfully. Verified done. THANKS
