### ISSUE TITLE
Pagy benchmark against Will Paginate

### ISSUE THREAD

**Issue by joshm1204** [mislav/will_paginate#596]
Pagy has made some claims on memory usage and speed against Kaminari and Will_paginate.

I am wondering if anyone has reviewed the benchmark results and came to the same conclusion?

https://github.com/ddnexus/pagy

I have been using Will_paginate and Kaminari for small projects and love them both, but I am concerned about memory usage on a much larger project with large datasets. Thoughts on pros and cons of each?

**Comment by mislav** [comment]
Thank you for linking!

will_paginate was my first ever Ruby library. Lately, I haven't had much time or motivation to maintain it or vastly improve it. I'm pretty sure that any newer pagination library will probably be faster! If speed is a concern, I would recommend solutions other than will_paginate. 🙇
