### ISSUE TITLE
how can i make this not summarise the numbers after 10?

### ISSUE THREAD

**Issue by silky** [mislav/will_paginate#598]
for example, i'm getting:

![image](https://user-images.githubusercontent.com/129525/63315907-41305f80-c350-11e9-9219-3cbef8f51b81.png)

how can i make it expand all the links? (and only the do the summary if that the number of pages exceeds 20, instead of 10.)

**Comment by mislav** [comment]
Try increasing the [`:inner_window` parameter](https://github.com/mislav/will_paginate/wiki/API-documentation#view-template-helpers):

```erb
<%= will_paginate @posts, inner_window: 20 %>
```
