### ISSUE TITLE
3.1.6 incompatible with active_record 5.2.4.1

### ISSUE THREAD

**Issue by bjones** [mislav/will_paginate#606]
It appears activerecord 5.2.3 through 5.2.4.1 has changed the API signature of select_for_count such that will_paginate's modifications to that private detail are broken.

wrong number of arguments (given 0, expected 1)
backtrace:
will_paginate-3.1.6/lib/will_paginate/active_record.rb:140:in `select_for_count'
activerecord-5.2.4.1/lib/active_record/relation/calculations.rb:226:in `perform_calculation'

**Comment by mislav** [comment]
Please upgrade will_paginate to at least 3.1.7 https://github.com/mislav/will_paginate/commit/c00a841f6aa554346318b1e86c25c4ada05d7fe2
