### ISSUE TITLE
ruby 2.7 warning

### ISSUE THREAD

**Issue by eladeyal-intel** [mislav/will_paginate#607]
I get this with ruby 2.7 

```
[...]vendor/bundle/ruby/2.7.0/gems/will_paginate-3.2.1/lib/will_paginate/railtie.rb:66: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

**Comment by eclectic-coding** [comment]
This is a warning, one of many, which started with Ruby 2.7. You can read about a work around to decrease the noise [here](https://prathamesh.tech/2019/12/26/managing-warnings-emitted-by-ruby-2-7/). 

Short work around:
Launch console with an environment variable:
`RUBYOPT='-W:no-deprecated -W:no-experimental' rails c`

Or (this is what I did) you can add `RUBYOPT` to your shell profile. I use ZSH so I added the following to my `.zshrc` file:
`export RUBYOPT='-W:no-deprecated -W:no-experimental'`

These are ways to quiet down the warnings.

**Comment by eladeyal-intel** [comment]
I think https://github.com/mislav/will_paginate/commit/1e26621a7c999fbb57f173359a06ebf1167cd42b was supposed to fix that. Let me bump-gem and check again.
