### ISSUE TITLE
Can there be better error encapsulation if the infered collection is nil as a result of being a hash (particularly a nested one)?  

### ISSUE THREAD

**Issue by Heizenburg** [mislav/will_paginate#612]
https://github.com/mislav/will_paginate/blob/8113fddf4b506867e9af3aa59fe2df314b79860c/lib/will_paginate/view_helpers/action_view.rb#L28

**Comment by mislav** [comment]
Hi, the inferring behavior is relatively simple:

```rhtml
<%= will_paginate %>
```

If the above runs in the context of a "users" controller, for instance, and no paginated collection was explicitly passed to `will_paginate`, the collection will try to be read from the `@users` variable.

This mechanism isn't great and doesn't cover a lot of the cases. I'm not proud that I've build the inferring behavior in the first place. I would suggest not using it and not relying on it, and instead doing:

```rhtml
<%= will_paginate @posts %>
```
