### ISSUE TITLE
How to remember checkbox which has been selected in previous page?

### ISSUE THREAD

**Issue by VedaRamaiah** [mislav/will_paginate#614]
I am using will_paginate to list a huge ammont of files in different pages. I also have a check_box in order to choose files for the futher analysis. 
Lets say, I have selected 2 checkboxes on the first page and clicked on page = 2 and selects 3 entries. Once I return back to first page, how to keep checkboxes still selected state?

**Comment by mislav** [comment]
When generating pagination links, will_paginate will forward all GET parameters passed to the first page (where pagination originated) to the next pages. This will include any parameters that were generated by checkboxes. Simply ensure that the checkboxes are pre-checked if their own GET parameter was supplied in the request, and you'll be good to go 👍
