### ISSUE TITLE
Routes error causes will_paginate to crash

### ISSUE THREAD

**Issue by DaniyalBasit** [mislav/will_paginate#617]
We are getting the following error message
```
arguments passed to url_for can't be handled. Please require routes or provide your own implementation
```
from
```
<%= will_paginate @meetings %>
```
Our code was working fine and we have been using it in Production for more than a year. This is now happening across all the applications. 

Note: I have disabled the **eager_loading** from the configs

**Comment by emorris** [comment]
same issue.. and for some reason after 3 years all this start to blow up. I guess no one is supporting this gem anymore

**Comment by DaniyalBasit** [comment]
Make sure that Rails execution stack is not breaking...

In our case we were calling an  ApplicationHelper before the ApplicationControllers

**Comment by mislav** [comment]
@DaniyalBasit Is this still an issue for you?

**Comment by DaniyalBasit** [comment]
@mislav not anymore
