### ISSUE TITLE
Wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by anjacquemin** [mislav/will_paginate#638]
Hello,

I have a problem I don't manage to fix.

Here is the code : 
- controller : 
def index
    @users = User.paginate(page: params[:page])
end

- view : 
<%= will_paginate @users%>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

Error (coming from will_paginate : 
- wrong number of arguments (given 2, expected 1)

Software : 
- rails 6.1.5.1
- will_paginate : 3.1.8 (I also tried .7 and .6)
- ruby : 3.0.3

Thank you for your help
Anthony

**Comment by anjacquemin** [comment]
Hello, 

Here is the full trace.

Tell me if you need anything else (hoping this time we'll manage to fix this issue :))

[actionview (6.1.5.1) lib/action_view/helpers/translation_helper.rb:70:in `translate'](http://localhost:3000/users#)
[will_paginate (3.1.8) lib/will_paginate/view_helpers/action_view.rb:83:in `will_paginate_translate'](http://localhost:3000/users#)
[will_paginate (3.1.8) lib/will_paginate/view_helpers.rb:77:in `will_paginate'](http://localhost:3000/users#)
[bootstrap-will_paginate (1.0.0) config/initializers/will_paginate.rb:15:in `will_paginate'](http://localhost:3000/users#)
[app/views/users/index.html.erb:4](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/base.rb:247:in `public_send'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/base.rb:247:in `_run'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/template.rb:154:in `block in render'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/notifications.rb:205:in `instrument'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/template.rb:345:in `instrument_render_template'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/template.rb:152:in `render'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/notifications.rb:203:in `block in instrument'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/notifications.rb:203:in `instrument'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/notifications.rb:203:in `block in instrument'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/notifications.rb:203:in `instrument'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/renderer/template_renderer.rb:55:in `render_template'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/renderer/template_renderer.rb:11:in `render'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/renderer/renderer.rb:29:in `render_to_object'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/rendering.rb:117:in `block in _render_template'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/base.rb:273:in `in_rendering_context'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/rendering.rb:116:in `_render_template'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/streaming.rb:218:in `_render_template'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/rendering.rb:103:in `render_to_body'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/abstract_controller/rendering.rb:25:in `render'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/rendering.rb:36:in `render'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'](http://localhost:3000/users#)
[/home/anthony/.rbenv/versions/3.0.3/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/instrumentation.rb:46:in `block in render'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'](http://localhost:3000/users#)
[activerecord (6.1.5.1) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/instrumentation.rb:45:in `render'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/implicit_render.rb:35:in `default_render'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'](http://localhost:3000/users#)
[<internal:kernel>:90:in `tap'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/abstract_controller/base.rb:228:in `process_action'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/rendering.rb:30:in `process_action'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/callbacks.rb:117:in `block in run_callbacks'](http://localhost:3000/users#)
[actiontext (6.1.5.1) lib/action_text/rendering.rb:20:in `with_renderer'](http://localhost:3000/users#)
[actiontext (6.1.5.1) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/callbacks.rb:126:in `instance_exec'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/callbacks.rb:137:in `run_callbacks'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/abstract_controller/callbacks.rb:41:in `process_action'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/rescue.rb:22:in `process_action'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/notifications.rb:203:in `block in instrument'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/notifications.rb:203:in `instrument'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'](http://localhost:3000/users#)
[activerecord (6.1.5.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/abstract_controller/base.rb:165:in `process'](http://localhost:3000/users#)
[actionview (6.1.5.1) lib/action_view/rendering.rb:39:in `process'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal.rb:190:in `dispatch'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_controller/metal.rb:254:in `dispatch'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/journey/router.rb:32:in `each'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/journey/router.rb:32:in `serve'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/routing/route_set.rb:842:in `call'](http://localhost:3000/users#)
[rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'](http://localhost:3000/users#)
[rack (2.2.3) lib/rack/etag.rb:27:in `call'](http://localhost:3000/users#)
[rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'](http://localhost:3000/users#)
[rack (2.2.3) lib/rack/head.rb:12:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/http/content_security_policy.rb:19:in `call'](http://localhost:3000/users#)
[rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'](http://localhost:3000/users#)
[rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'](http://localhost:3000/users#)
[activerecord (6.1.5.1) lib/active_record/migration.rb:601:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/callbacks.rb:98:in `run_callbacks'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'](http://localhost:3000/users#)
[web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'](http://localhost:3000/users#)
[web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'](http://localhost:3000/users#)
[web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'](http://localhost:3000/users#)
[web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'](http://localhost:3000/users#)
[railties (6.1.5.1) lib/rails/rack/logger.rb:37:in `call_app'](http://localhost:3000/users#)
[railties (6.1.5.1) lib/rails/rack/logger.rb:26:in `block in call'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/tagged_logging.rb:37:in `tagged'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/tagged_logging.rb:99:in `tagged'](http://localhost:3000/users#)
[railties (6.1.5.1) lib/rails/rack/logger.rb:26:in `call'](http://localhost:3000/users#)
[sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'](http://localhost:3000/users#)
[rack (2.2.3) lib/rack/method_override.rb:24:in `call'](http://localhost:3000/users#)
[rack (2.2.3) lib/rack/runtime.rb:22:in `call'](http://localhost:3000/users#)
[activesupport (6.1.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/static.rb:24:in `call'](http://localhost:3000/users#)
[rack (2.2.3) lib/rack/sendfile.rb:110:in `call'](http://localhost:3000/users#)
[actionpack (6.1.5.1) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'](http://localhost:3000/users#)
[rack-mini-profiler (2.3.4) lib/mini_profiler/profiler.rb:393:in `call'](http://localhost:3000/users#)
[webpacker (5.4.3) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'](http://localhost:3000/users#)
[rack-proxy (0.7.2) lib/rack/proxy.rb:67:in `call'](http://localhost:3000/users#)
[railties (6.1.5.1) lib/rails/engine.rb:539:in `call'](http://localhost:3000/users#)
[puma (5.6.4) lib/puma/configuration.rb:252:in `call'](http://localhost:3000/users#)
[puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'](http://localhost:3000/users#)
[puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'](http://localhost:3000/users#)
[puma (5.6.4) lib/puma/request.rb:76:in `handle_request'](http://localhost:3000/users#)
[puma (5.6.4) lib/puma/server.rb:441:in `process_client'](http://localhost:3000/users#)
[puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'](http://localhost:3000/users#)

**Comment by mislav** [comment]
Thank you! Could you try upgrading will_paginate in your app? This problem might have been fixed with https://github.com/mislav/will_paginate/commit/1e26621a7c999fbb57f173359a06ebf1167cd42b

**Comment by anjacquemin** [comment]
Thanks, everything is working now ! I missed v.3.3.x of will_paginate.
